import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const Roboto= localFont({
  src: "./fonts/roboto/roboto-500.woff2",
  variable: "--font-roboto-500",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Ondřej Losenský",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Roboto.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
